versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.04.28:
    folder: all
  1.90.0-develop+25.04.28.13.47:
    folder: all
  1.90.0-master+25.04.28:
    folder: all
  1.90.0-master+25.04.28.13.47:
    folder: all
