versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.04.15:
    folder: all
  1.90.0-develop+25.04.15.18.33:
    folder: all
  1.90.0-master+25.04.15:
    folder: all
  1.90.0-master+25.04.15.18.33:
    folder: all
