versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.08.25:
    folder: all
  1.90.0-develop+25.08.25.19.05:
    folder: all
  1.90.0-master+25.08.25:
    folder: all
  1.90.0-master+25.08.25.19.05:
    folder: all
