versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.03.21:
    folder: all
  1.90.0-develop+25.03.21.17.00:
    folder: all
  1.90.0-master+25.03.21:
    folder: all
  1.90.0-master+25.03.21.17.00:
    folder: all
