versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.06.26:
    folder: all
  1.90.0-develop+25.06.26.09.00:
    folder: all
  1.90.0-master+23.04.17:
    folder: all
  1.90.0-master+23.04.17.06.59:
    folder: all
