= Boost Conan Index

Conan package recipe index for Boost libraries. The project can be cloned and
used as a
https://docs.conan.io/2/tutorial/conan_repositories/setup_local_recipes_index.html[
local recipe index].

The index contains packages for Boost libraries separately and not as
a monolith. There are versions of packages that correspond to Boost releases
and nightly versions creates from the state of Boost superproject each day
based on develop and master branches. Release package have Conan refs like
`boost-LIBRARY/MAJOR.MINOR.PATCH` (e.g. `boost-range/1.89.0`). Nightly packages
have Conan refs like `boost-LIBRARY/MAJOR.MINOR.0-BRANCH+YY.MM.DD` (e.g.
`boost-config/1.90.0-master+25.07.04`). In this latter case, `MAJOR.MINOR.0` is
the Boost version that was planned to be the next at the time of the package
creation. `BRANCH` is the branch of the Boost superproject that was used to
create the packages. `YY.MM.DD` is the date the specific commit referred to by
the package was authored (year is used without the century digits).

NOTE: Nightly packages' version structure makes them prereleases (which they in
fact are). Conan doesn't find prerelease versions unless it is
https://docs.conan.io/2/devops/versioning/resolve_prereleases.html[allowed to
do so].

== Install

```sh
git clone https://github.com/grisumbras/boost-conan-index -b index --depth 1
conan remote add boost-conan-index ./boost-conan-index
```

To update the index
```sh
git -C boost-conan-index pull
```

== Usage

When added the recipe index behaves like a regular conan remote. However note
that the index doesn't provide any prebuilt packages, thus anything installed
from it would require a `--build=missing` or a similar flag (see
https://docs.conan.io/2/reference/commands/install.html[`conan install`
documentation]).

Prereleases are sorted as tuples of `(version, prerelease, build)`.
Alphanumeric components are sorted lexicographically. Hence, given packages
`boost-config/1.90.0-develop+25.1.2` and `boost-config/1.90.0-master+25.1.1`,
the latter is consider more recent (`master` is greater than `develop`
lexicographically).

Don't forget to use `-u` or `--update` in Conan commands to get the more recent
packages from the index rather than using the versions you already have in
local cache.

=== Example Version Requests

Boost.Any from the Boost release 1.89.0:: `boost-any/1.89.0`

Most recent released version of Boost.Any:: `boost-any/[*]`

Most recent version of Boost.Any, including prereleases::
`boost-any/[>0-a, include_prerelease]`

Most recent nightly version of Boost.Any before release 1.90.0::
`boost-any/[<1.90.0-z, include_prerelease]`

Most recent version of Boost.Any from master before release 1.90.0::
`boost-any/[>=1.90.0-master <1.90.0-z, include_prerelease]`

Most recent version of Boost.Any from develop before release 1.90.0::
`boost-any/[>=1.90.0-develop <1.90.0-master, include_prerelease]`

Most recent version of Boost.Any from develop before release 1.90.0, authored before July 2025::
`boost-any/[<1.90.0-develop+2025.07, include_prerelease]`

Most recent version of Boost.Any from master before release 1.90.0, authored in July 2025::
`boost-any/[>=1.90.0-master+2025.07 <1.90.0-master+2025.08, include_prerelease]`

== Contributing

Contributions are welcome.

== License

link:LICENSE_1_0.txt[BSL-1.0] (C) 2025 Dmitry Arkhipov <grisumbras@yandex.ru>.
