versions:
  1.89.0:
    folder: all
  1.90.0-develop+24.12.14:
    folder: all
  1.90.0-develop+24.12.14.05.05:
    folder: all
  1.90.0-master+24.12.14:
    folder: all
  1.90.0-master+24.12.14.05.05:
    folder: all
