versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.08.17:
    folder: all
  1.90.0-develop+25.08.17.15.33:
    folder: all
  1.90.0-master+25.01.18:
    folder: all
  1.90.0-master+25.01.18.23.55:
    folder: all
