versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.04.03:
    folder: all
  1.90.0-develop+25.04.03.14.10:
    folder: all
  1.90.0-master+25.04.03:
    folder: all
  1.90.0-master+25.04.03.14.10:
    folder: all
