versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.09.12:
    folder: all
  1.90.0-develop+25.09.12.22.13:
    folder: all
  1.90.0-master+25.09.12:
    folder: all
  1.90.0-master+25.09.12.22.39:
    folder: all
