versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.06.28:
    folder: all
  1.90.0-develop+25.06.28.11.02:
    folder: all
  1.90.0-master+24.12.28:
    folder: all
  1.90.0-master+24.12.28.22.04:
    folder: all
