versions:
  1.89.0:
    folder: all
  1.90.0-develop+24.08.18:
    folder: all
  1.90.0-develop+24.08.18.11.52:
    folder: all
  1.90.0-master+21.06.04:
    folder: all
  1.90.0-master+21.06.04.22.00:
    folder: all
