versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.08.25:
    folder: all
  1.90.0-develop+25.08.25.23.15:
    folder: all
  1.90.0-master+25.05.20:
    folder: all
  1.90.0-master+25.05.20.09.17:
    folder: all
