versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.07.02:
    folder: all
  1.90.0-develop+25.07.02.08.14:
    folder: all
  1.90.0-master+25.01.01:
    folder: all
  1.90.0-master+25.01.01.20.44:
    folder: all
