versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.07.07:
    folder: all
  1.90.0-develop+25.07.07.06.39:
    folder: all
  1.90.0-master+22.10.31:
    folder: all
  1.90.0-master+22.10.31.09.22:
    folder: all
