versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.09.09:
    folder: all
  1.90.0-develop+25.09.09.16.43:
    folder: all
  1.90.0-master+25.09.09:
    folder: all
  1.90.0-master+25.09.09.16.43:
    folder: all
