versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.05.02:
    folder: all
  1.90.0-develop+25.05.02.19.11:
    folder: all
  1.90.0-master+25.01.26:
    folder: all
  1.90.0-master+25.01.26.17.47:
    folder: all
