versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.06.25:
    folder: all
  1.90.0-develop+25.06.25.18.43:
    folder: all
  1.90.0-master+21.09.14:
    folder: all
  1.90.0-master+21.09.14.23.10:
    folder: all
