versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.08.26:
    folder: all
  1.90.0-develop+25.08.26.15.44:
    folder: all
  1.90.0-master+25.08.26:
    folder: all
  1.90.0-master+25.08.26.15.44:
    folder: all
