versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.05.02:
    folder: all
  1.90.0-develop+25.05.02.19.22:
    folder: all
  1.90.0-master+21.05.28:
    folder: all
  1.90.0-master+21.05.28.00.26:
    folder: all
