versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.05.02:
    folder: all
  1.90.0-develop+25.05.02.19.12:
    folder: all
  1.90.0-master+22.01.29:
    folder: all
  1.90.0-master+22.01.29.06.44:
    folder: all
