name: CI

on:
  push:
  schedule:
    - cron: '0 11 * * *'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  Generate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        boost-ref: &boost-refs
          - boost-1.90.0.beta1

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate index
        run: tools/generate.py --ref  ${{ matrix.boost-ref }} --target index

      - name: Save index
        uses: actions/upload-artifact@v4
        with:
          name: index-${{ matrix.boost-ref }}
          path: |
            index/
            !**/build/
          if-no-files-found: error
          retention-days: 1
          compression-level: 9

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    needs: Generate
    strategy:
      matrix:
        toolset:
          - msvc

    steps:
      - name: Fetch head
        uses: actions/checkout@v5

      - name: Download new indices
        uses: actions/download-artifact@v5
        with:
          name: index-boost-1.90.0.beta1
          path: index

      - uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Setup Conan
        run: |
          set -ex

          pip install conan
          conan remote add boost-conan-index ./index

      - name: Test selected packages
        run: |
          set -ex

          for proj in boost-core; do
            conan test --build=missing \
                -pr:a ./test/windows-${{ matrix.toolset }}.profile \
                "index/recipes/$proj/all/test_package" \
                "$proj/[>0-a,include_prerelease]"
          done

          workdir=$(pwd)
          package_id=$(conan list 'boost-core/*:*' 2>1 | sed -n '7p' | sed 's/^\s*//')
          build_dir=$(conan cache path --folder build boost-core/1.90.0-b.1:$package_id)
          cd $build_dir
          ls bin.v2
          ls bin.v2\\generators
          rm -rf bin.v2\\boost
          conan run "b2 libs/core//conan-install --project-config=bin.v2\\generators\\project-config.jam --build-dir=bin.v2 install-prefix=..\\p toolset=msvc cxxstd=20 link=static architecture=x86 address-model=64 target-os=windows --requested-libraries= -d+2 --reconfigure" \
            --tool-requires=b2/5.3.3 \
            -pr:a $workdir/test/windows-${{ matrix.toolset }}.profile
