versions:
  1.89.0:
    folder: all
  1.90.0-develop+25.06.09:
    folder: all
  1.90.0-develop+25.06.09.02.44:
    folder: all
  1.90.0-master+25.06.09:
    folder: all
  1.90.0-master+25.06.09.02.44:
    folder: all
